---
- name: Remove user account on target server
  user:
    name: "{{ snwl_name }}"
    state: "{{ snwl_state }}"
    remove: "{{ snwl_remove }}"

- name: Remove sudoers file for the ansible user
  file:
    path: /etc/sudoers.d/99-ansible-user
    state: "{{ snwl_state }}"
